#!/usr/bin/env bash

if [[ ! -z "$DATABASE_URL" ]]
 then
    export DB_TYPE=`php -r "echo parse_url(getenv('DATABASE_URL'), PHP_URL_SCHEME);"`
    export DB_HOST=`php -r "echo parse_url(getenv('DATABASE_URL'), PHP_URL_HOST);"`
    export DB_PORT=`php -r "echo parse_url(getenv('DATABASE_URL'), PHP_URL_PORT);"`
    export DB_DATABASE=`php -r "echo str_replace('/','',parse_url(getenv('DATABASE_URL'), PHP_URL_PATH));"`
    export DB_USERNAME=`php -r "echo parse_url(getenv('DATABASE_URL'), PHP_URL_USER);"`
    export DB_PASSWORD=`php -r "echo parse_url(getenv('DATABASE_URL'), PHP_URL_PASS);"`
fi